### ISSUE TITLE
Code Help

### ISSUE THREAD

**Issue by DanielAD84** [mozilla-it/plowforce#12]
Your Golang code looks so different than simpleforce and go-sfdc. I'm new to golang and I'm required to write an API what's the difference between set method, map, and just listing the objects? I appreciate any time or any samples of a large implementation. Thanks!

**Comment by marty331** [comment]
@DanielAD84 The set method you are referring to is specific to the simpleforce repo, it's just as it sounds, it's setting a value.  Map is simply creating a data map, similar to a JSON object or a Dict in Python.
